spring:
  profiles: LOCAL, default, test
  datasource:
    url: ${DB_CONNECTION_STRING:defaultDbConnectionString}
    username: ${DB_USER:defaultDbUser}
    password: ${DB_PASSWORD:defaultPassword}
    initialization-mode: always
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
    jpa:
      database: postgresql
      hibernate:
        ddl-auto: create
      properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
flyway:
  url: ${DB_CONNECTION_STRING:defaultDbConnectionString}
  user: ${DB_USER:defaultDbUser}
  password: ${DB_PASSWORD:defaultDbPassword}
  schemas: ["public"]
---
spring:
  profiles: PROD
  datasource:
    url: ${DB_CONNECTION_STRING:defaultDbConnectionString}
    username: ${DB_USER:defaultDbUser}
    password: ${DB_PASSWORD:defaultDbPassword}
    initialization-mode: always
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
    jpa:
      database: postgresql
      hibernate:
        ddl-auto: create
      properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
flyway:
  url: ${DB_CONNECTION_STRING:defaultDbConnectionString}
  user: ${DB_USER:defaultDbUser}
  password: ${DB_PASSWORD:defaultDbPassword}
  schemas: [ "public" ]
