spring:
  profiles: LOCAL, default, test
  datasource:
    url: ${DB_CONNECTION_STRING:defaultDbConnectionString}
    username: ${DB_USER:defaultDbUser}
    password: ${DB_PASSWORD:defaultPassword}
  hikari:
    minimum-idle: 2
    maximum-pool-size: 4
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${DB_CONNECTION_STRING:defaultDbConnectionString}
    user: ${DB_USER:defaultDbUser}
    password: ${DB_PASSWORD:defaultDbPassword}
    schemas: ["public"]
    baseline-on-migrate: true
# docker-compose local db url = jdbc:postgresql://192.168.99.100:5432/d303tt7dgo2ndl?currentSchema=public
---
spring:
  profiles: PROD
  datasource:
    url: ${DB_CONNECTION_STRING:defaultDbConnectionString}
    username: ${DB_USER:defaultDbUser}
    password: ${DB_PASSWORD:defaultDbPassword}
  hikari:
    minimum-idle: 2
    maximum-pool-size: 4
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${DB_CONNECTION_STRING:defaultDbConnectionString}
    user: ${DB_USER:defaultDbUser}
    password: ${DB_PASSWORD:defaultDbPassword}
    schemas: [ "public" ]
    baseline-on-migrate: true